development:
  adapter: postgresql
  encoding: unicode
  database: class-sap_development
  pool: 5
  username: abbeytipton
  password:
  timeout: 5000

  test:
  adapter: postgresql
  encoding: unicode
  database: class-sap_test
  pool: 5
  username: abbeytipton
  password:
  timeout: 5000
